"""empty message

Revision ID: d1fe11108b31
Revises: 
Create Date: 2019-12-31 14:01:01.204038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fe11108b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer1', sa.String(length=100), nullable=True),
    sa.Column('answer2', sa.String(length=100), nullable=True),
    sa.Column('answer3', sa.String(length=100), nullable=True),
    sa.Column('right_answer', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizz')
    # ### end Alembic commands ###
