"""empty message

Revision ID: e93fcb009688
Revises: d92cb01fe916
Create Date: 2020-01-08 17:08:53.744295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e93fcb009688'
down_revision = 'd92cb01fe916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
